CREATE TABLE [dbo].[FoodCategory]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FoodCategory] ADD CONSTRAINT [PK__FoodCate__3214EC075ABB1B95] PRIMARY KEY CLUSTERED ([Id]) ON [PRIMARY]
GO
